---
- name: variables in ansible  
  hosts: user
  vars: 
    course: DevOps
    trainer: siva
    duration: 60days
  tasks: 
  - name: print helloworld
    ansible.builtin.debug:
     msg: " hello world"
  - name: print variables
    ansible.builtin.debug:
     msg: " hello, i am learning {{course}}, {{trainer}}, {{duration}}"